all: main

main: Controller.cpp Controller.hpp Draw.cpp Draw.hpp main.cpp B-Tree.c B-Tree.h DinamicVector.c DinamicVector.h
	g++ main.cpp Controller.cpp Draw.cpp B-Tree.c DinamicVector.c -o main -Wall

